Allow storing the key in an unencrypted file.

diff --git a/gandi-mail b/gandi-mail
--- a/gandi-mail
+++ b/gandi-mail
@@ -12,7 +12,7 @@ CURL_OUTPUT=$(mktemp)
 trap "rm '$CURL_OUTPUT'" EXIT
 
 usage() {
-  cat <<-HELP
+  cat 1>&2 <<-HELP
 	Usage $0 [command]
 
 	  COMMANDS:
@@ -31,10 +31,21 @@ usage() {
 }
 
 api_request() {
-  if [ -z "${GANDI_TOKEN:-}" ]
+  if [ -z "${GANDI_KEY:-}" ]
   then
-    local CONFIG_DIR=${XDG_CONFIG_HOME:-$HOME/.config}/gandi-emails
-    GANDI_TOKEN=$(gpg -qd "$CONFIG_DIR/api-key.gpg")
+    local config_dir=${XDG_CONFIG_HOME:-$HOME/.config}/gandi-emails
+    local key_file="$config_dir/api-key"
+
+    if [ -f "$key_file.gpg" ]
+    then
+      GANDI_KEY=$(gpg -qd "$key_file.gpg")
+    elif [ -f "$key_file" ]
+    then
+      GANDI_KEY=$(cat "$key_file")
+    else
+      echo "Missing key file." 1>&2
+      usage
+    fi
   fi
 
   local url="$GANDI_ORIGIN$1"
@@ -46,11 +57,11 @@ api_request() {
     body=(-H "Content-Type: application/json" --data-binary @-)
   fi
 
-  curl --silent --fail --tlsv1.3            \
-    -H "Authorization: Apikey $GANDI_TOKEN" \
-    --output "$CURL_OUTPUT"                 \
-    "$url"                                  \
-    "$@"                                    \
+  curl --silent --fail --tlsv1.3          \
+    -H "Authorization: Apikey $GANDI_KEY" \
+    --output "$CURL_OUTPUT"               \
+    "$url"                                \
+    "$@"                                  \
     "${body[@]}" || (
       printf "Request to %s failed\n" "$url" 1>&2
       cat "$CURL_OUTPUT" 1>&2
